import { Song } from "./types";

export const MOCK_SONGS: Song[] = [
  {
    id: "1",
    title: "Midnight City",
    artist: "M83",
    album: "Hurry Up, We're Dreaming",
    genre: "Electronic",
    duration: "4:03",
    favorite: true,
    playCount: 150,
    coverUrl: "https://picsum.photos/seed/m83/300/300",
  },
  {
    id: "2",
    title: "Starboy",
    artist: "The Weeknd",
    album: "Starboy",
    genre: "R&B",
    duration: "3:50",
    favorite: false,
    playCount: 230,
    coverUrl: "https://picsum.photos/seed/weeknd/300/300",
  },
  {
    id: "3",
    title: "Levitating",
    artist: "Dua Lipa",
    album: "Future Nostalgia",
    genre: "Pop",
    duration: "3:23",
    favorite: true,
    playCount: 410,
    coverUrl: "https://picsum.photos/seed/dualipa/300/300",
  },
  {
    id: "4",
    title: "Blinding Lights",
    artist: "The Weeknd",
    album: "After Hours",
    genre: "Pop",
    duration: "3:20",
    favorite: true,
    playCount: 500,
    coverUrl: "https://picsum.photos/seed/blinding/300/300",
  },
  {
    id: "5",
    title: "Instant Crush",
    artist: "Daft Punk",
    album: "Random Access Memories",
    genre: "Electronic",
    duration: "5:37",
    favorite: false,
    playCount: 120,
    coverUrl: "https://picsum.photos/seed/daft/300/300",
  },
  {
    id: "6",
    title: "Heat Waves",
    artist: "Glass Animals",
    album: "Dreamland",
    genre: "Indie",
    duration: "3:58",
    favorite: false,
    playCount: 340,
    coverUrl: "https://picsum.photos/seed/glass/300/300",
  },
  {
    id: "7",
    title: "Save Your Tears",
    artist: "The Weeknd",
    album: "After Hours",
    genre: "Pop",
    duration: "3:35",
    favorite: true,
    playCount: 280,
    coverUrl: "https://picsum.photos/seed/save/300/300",
  },
  {
    id: "8",
    title: "One More Time",
    artist: "Daft Punk",
    album: "Discovery",
    genre: "Electronic",
    duration: "5:20",
    favorite: true,
    playCount: 190,
    coverUrl: "https://picsum.photos/seed/onemore/300/300",
  },
];
